- name: hth-java
  src: https://github.com/hrafnthor/ansible-java.git
  scm: git
  version: "0.0.1"
- name: hth-gradle
  src: https://github.com/hrafnthor/ansible-gradle.git
  scm: git
  version: "0.0.1"
- name: hth-android-sdk
  src: https://github.com/hrafnthor/ansible-android-sdk.git
  scm: git
  version: "0.0.1"
- name: hth-android-studio
  src: https://github.com/hrafnthor/ansible-android-studio.git
  scm: git
  version: "0.0.1"