- name: hth-java
  src: https://github.com/hrafnthor/ansible-java.git
  scm: git
  version: "0.0.1"
- name: hth-gradle
  src: https://github.com/hrafnthor/ansible-gradle.git
  scm: git
  version: "0.0.1"